#!/bin/sh

# 日志记录格式 (Log format)
# $year-$month-$day $hour:$minute:$second $log_text

# 获取当前路径 (Get current path)
current_path=$(pwd)
# 设置日志路径 (Set log file path)
log_file_name="$current_path/../upload.log"

# 转换图片格式 (Convert image format)
# 写入日志: "图片格式开始转换 (Image format conversion started)"
echo "$(date '+%Y-%m-%d %H:%M:%S') 1.图片格式开始转换(Image format conversion started)..." >> "$log_file_name"
# 执行 imageToAVIF (Execute imageToAVIF)
../ImageToAVIF/ImageToAVIF.exe ./assets &>> "$log_file_name"
# 检查 imageToAVIF 执行是否成功 (Check if imageToAVIF execution is successful)
if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') 1.图片格式转换失败(Image format conversion failed)..." >> "$log_file_name"
    # 如果失败, 退出脚本 (If failed, exit the script)
    exit 1
fi
echo "$(date '+%Y-%m-%d %H:%M:%S') 1.图片格式转换完成(Image format conversion completed)..." >> "$log_file_name"

# 生成发布网页 (Generate publish web page)
# 写入日志: "发布网页开始生成 (Publish web page generation started)"
echo "$(date '+%Y-%m-%d %H:%M:%S') 2.发布网页开始生成(Publish web page generation started)..." >> "$log_file_name"
# 执行 logseq-publish-spa out (Execute logseq-publish-spa out)
../Node/logseq-publish-spa ../PublishWeb &>> "$log_file_name"
# 检查 logseq-publish-spa 执行是否成功 (Check if logseq-publish-spa execution is successful)
if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') 2.发布网页生成失败(Publish web page generation failed)..." >> "$log_file_name"
    # 如果失败, 退出脚本 (If failed, exit the script)
    exit 1
fi
echo "$(date '+%Y-%m-%d %H:%M:%S') 2.发布网页生成完成(Publish web page generation completed)..." >> "$log_file_name"

# 同步到Github远程仓库 (Synchronize to Github remote repository)
# 写入日志: "发布网页开始上传 (Publish web page upload started)"
echo "$(date '+%Y-%m-%d %H:%M:%S') 3.发布网页开始上传(Publish web page upload started)..." >> "$log_file_name"
# 进入 ../PublishWeb 目录 (Enter ../PublishWeb directory)
cd ../PublishWeb
# 添加所有更改 (Add all changes)
git add -A
git commit -m "Logseq Auto Publish" &>> "$log_file_name"
# 推送到远程仓库的 main 分支 (Push to the main branch of remote repository)
git push origin main &>> "$log_file_name"
if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') 3.发布网页上传失败(Publish web page upload failed)..." >> "$log_file_name"
    # 如果失败, 退出脚本 (If failed, exit the script)
    exit 1
else
    echo "$(date '+%Y-%m-%d %H:%M:%S') 3.发布网页上传完成(Publish web page upload completed)..." >> "$log_file_name"
fi


# 写入日志: "结束上传 (End of upload)"
echo "$(date '+%Y-%m-%d %H:%M:%S') 结束上传(End of upload)..." >> "$log_file_name"