name: Delete old workflow runs
on:
# Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for remote repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: '...'
          retain_days: 14
          keep_minimum_runs: 1
  cleanup:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Delete deployment
          uses: strumwolf/delete-deployment-environment@v3.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            environment: github-pages
            onlyRemoveDeployments: true